### ISSUE TITLE
Replace deprecated `wait()` function with `task.wait()`

### ISSUE THREAD

**Issue by Aulkhami** [weebweeb/ParticleGun_rbx#1]
`wait()` can throttle, unlike `task.wait()`, which resumes the thread on the first heartbeat that occurs when it is due.

References:
https://create.roblox.com/docs/reference/engine/libraries/task#wait
https://create.roblox.com/docs/reference/engine/globals/RobloxGlobals#wait

**Comment by Aulkhami** [comment]
Unless if you have a specific reason to use `wait()`.

**Comment by weebweeb** [comment]
I'll take a look to see if the change disrupts the timing of the ParticleEmitters. Thanks!

**Comment by weebweeb** [comment]
Merged the change with the main branch. No change to the timing. Thanks!
